Repository accordproject/markdown-editor, pull requests merged in 2019-07, with the labels that each got.

#66 feat(*): ap design sync - I35
  README.md
  assets/APLogo.png
  examples/src/index.js
  package-lock.json
  package.json
  src/FormatToolbar.js
  src/FormatToolbar/index.js
  src/FormatToolbar/toolbar.css
  src/FormatToolbar/toolbarMethods.js
  src/FormatToolbar/toolbarStyles.js
  src/FormatToolbar/toolbarTooltip.js
  src/SlateAsInputEditor/index.js
Labels: enhancement

#71 refactor(*): various refactoring to fix issues that cause component not to render in some cases
  package-lock.json
  package.json
  src/FormatToolbar/index.js
  src/SlateAsInputEditor/index.js
  src/styles.css
Labels: bug

#73 fix(icons): sync sizing for all toolbar icons - I62
  src/icons/OL.js
  src/icons/UL.js
  src/icons/bold.js
  src/icons/code.js
  src/icons/hyperlink.js
  src/icons/italic.js
  src/icons/navigation-left.js
  src/icons/navigation-right.js
  src/icons/open-quote.js
  src/icons/param.js
  src/icons/underline.js
Labels: bug, good first issue
