Repository accordproject/markdown-editor, pull requests merged in 2019-11, with the labels that each got.

#178 feat(schema): force next block after html to paragraph
  package-lock.json
  package.json
  src/schema.js
Labels: Difficulty: Medium, Type: Enhancement ✨

#180 fix(SlateAsInputEditor): always pass List and NoEdit plugins to editor
  src/SlateAsInputEditor/index.js
Labels: Type: Bug 🐛

#183 chore(test): pause roundtrip test
  src/SlateAsInputEditor/index.test.js
Labels: Type: Tests 🧪

#185 fix(*): fix toggling of bold and italics
  examples/src/index.js
  package-lock.json
  package.json
  src/PluginManager.js
  src/SlateAsInputEditor/index.js
  src/SlateAsInputEditor/index.test.js
  src/plugins/noedit.js
Labels: Type: Bug 🐛

#186 fix(FormattingToolbar): do not allow toolbar actions on text that should be locked
  src/FormattingToolbar/index.js
Labels: Type: Bug 🐛

#188 fix(schema): support softbreaks in lists - I187
  package-lock.json
  package.json
  src/schema.js
Labels: Difficulty: Starter, Type: Bug 🐛

#166 test(FormattingToolbar): init tests for buttons
  src/FormattingToolbar/index.test.js
Labels: Difficulty: Starter, Hacktoberfest, Type: Tests 🧪

#197 fix(SlateAsInputEditor): disallow cut functionality if in uneditable text
  package-lock.json
  src/SlateAsInputEditor/index.js
Labels: Type: Bug 🐛

#200 fix(SlateAsInputEditor): disallow paste if in non-editable text
  src/SlateAsInputEditor/index.js
Labels: Type: Bug 🐛

#202 fix(SlateAsInputEditor): fix bug where first key press edited non-editable text
  package-lock.json
  src/SlateAsInputEditor/index.js
Labels: Difficulty: Medium, Type: Bug 🐛

#203 refactor(*): pass editor to isEditable so it can be used by plugins
  package-lock.json
  package.json
  src/FormattingToolbar/index.js
  src/PluginManager.js
  src/SlateAsInputEditor/index.js
Labels: Type: Breaking Change 💥

#204 fix(src): support heading actions
  package-lock.json
  package.json
  src/FormattingToolbar/index.js
  src/FormattingToolbar/toolbarMethods.js
  src/constants.js
Labels: Difficulty: Starter, Type: Bug 🐛
