Repository accordproject/markdown-editor, pull requests merged in 2019-06, with the labels that each got.

#46 feat(markdown-editor): split editor into MarkdownAsInputEditor and SlateAsInputEditor
  examples/src/index.js
  package-lock.json
  src/FormatToolbar.js
  src/MarkdownAsInputEditor/index.js
  src/MarkdownEditor/index.js
  src/SlateAsInputEditor/default.js
  src/SlateAsInputEditor/index.js
  src/icons/OL.js
  src/icons/UL.js
  src/icons/bold.js
  src/icons/code.js
  src/icons/hyperlink.js
  src/icons/italic.js
  src/icons/navigation-left.js
  src/icons/navigation-right.js
  src/icons/open-quote.js
  src/icons/param.js
  src/icons/underline.js
  src/index.js
Labels: enhancement

#49 fix(FormatToolbar): correct responsive design for static toolbar - I48
  package-lock.json
  src/FormatToolbar.js
  src/MarkdownEditor/index.js
  src/SlateAsInputEditor/index.js
  src/styles.css
  src/toolbar.css
Labels: bug, enhancement

#50 feat(FormatToolbar): implement header style toolbar buttons - I20
  package-lock.json
  package.json
  src/FormatToolbar.js
  src/MarkdownEditor/index.js
  src/SlateAsInputEditor/index.js
  src/plugins/video.js
  src/styles.css
  src/toolbar.css
Labels: enhancement

#51 fix(SlateAsInputEditor): edit useEffect hook so it does not cause loop
  src/SlateAsInputEditor/index.js
Labels: bug

#56 docs(*): update guidelines for contributions - I55
  CONTRIBUTING.md
  DEVELOPERS.md
  README.md
  public/APLogo.png
Labels: enhancement

#60 docs(github): implement pr and issue templates - I55
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom-issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: enhancement

#61 refactor(FormatToolbar): remove parameter icon with css adjustments - I52
  package-lock.json
  package.json
  src/FormatToolbar.js
  src/toolbar.css
Labels: good first issue

#64 feat(MarkdownAsInputEditor): add readOnly prop for MarkdownAsInputEditor
  src/MarkdownAsInputEditor/index.js
Labels: enhancement
