Repository accordproject/markdown-editor, pull requests merged in 2019-10, with the labels that each got.

#93 docs(README): add downloads badge
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#94 Fix list blocks register as hyperlink (#84)
  src/FormattingToolbar/index.js
Labels: Difficulty: Medium, Hacktoberfest, Type: Bug 🐛

#92 feat: add serif `font-family` for all headings
  src/FormattingToolbar/index.js
  src/SlateAsInputEditor/index.js
Labels: Difficulty: Medium, Hacktoberfest

#103 docs(README): centered logo, adds slack badge, adds license badge
  README.md
Labels: Hacktoberfest, Type: Documentation 📝

#106 docs(README): fix typo - I104
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#115 fix(icons): remove id attribute from svg icons - I109
  src/icons/OL.js
  src/icons/UL.js
  src/icons/bold.js
  src/icons/code.js
  src/icons/hyperlink.js
  src/icons/italic.js
  src/icons/navigation-left.js
  src/icons/navigation-right.js
  src/icons/open-quote.js
  src/icons/param.js
  src/icons/underline.js
Labels: A11Y 🔓, Difficulty: Medium, Hacktoberfest

#110 doc(Readme): Centering heading and labelled badges
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#118 docs(README): add license and build badge
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#119 docs(CONTRIBUTING): fix typos
  CONTRIBUTING.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#138 feat(docs): add ecosystem table
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#136 fix(SlateAsInputEditor): set data-key for headings - I135
  src/SlateAsInputEditor/index.js
Labels: Difficulty: Medium, Hacktoberfest, Type: Bug 🐛

#140 chore(gitignore): add thumbs.db
  .gitignore
Labels: Difficulty: Starter, Hacktoberfest

#134 test(SlateAsInputEditor): init unit tests for md output - I2
  package.json
  src/SlateAsInputEditor/index.test.js
Labels: Difficulty: Medium, Hacktoberfest, Type: Tests 🧪

#142 feat(FormattingToolbar): implement hyperlink tooltip - I100
  src/FormattingToolbar/index.js
  src/FormattingToolbar/toolbarMethods.js
Labels: Difficulty: Medium, Hacktoberfest, Type: Feature Request 🛍️

#107 feat(*): styling for code blocks - I101
  README.md
  examples/src/index.js
  package-lock.json
  package.json
  src/SlateAsInputEditor/index.js
Labels: Difficulty: Challenging, Hacktoberfest, Type: Feature Request 🛍️

#144 feat(*): allow quote indent props styling - I125
  README.md
  src/SlateAsInputEditor/index.js
Labels: Difficulty: Starter, Hacktoberfest, Type: Enhancement ✨

#149 fix(SlateAsInputEditor): fix escaping out of list
  src/SlateAsInputEditor/index.js
Labels: Difficulty: Medium, Hacktoberfest

#153 fix(docs): typo in git upstream link - I151
  DEVELOPERS.md
Labels: Difficulty: Starter, Hacktoberfest

#150 fix(FormattingToolbar): toolbar buttons work in locktext mode
  src/FormattingToolbar/index.js
  src/SlateAsInputEditor/index.js
Labels: Difficulty: Medium, Hacktoberfest

#148 feat(*): allow styling for shadow and border - I124
  README.md
  src/SlateAsInputEditor/index.js
Labels: Difficulty: Starter, Hacktoberfest

#158 refactor(SlateAsInputEditor): remove styling props so user can style with own css
  README.md
  package-lock.json
  package.json
  src/SlateAsInputEditor/index.js
Labels: Type: Regression 🖐

#160 fix(src): pass shadow props
  src/SlateAsInputEditor/index.js
Labels: Type: Bug 🐛

#165 fix(icons): history aria-labels - I164
  src/icons/navigation-left.js
  src/icons/navigation-right.js
Labels: A11Y 🔓, Difficulty: Starter, Hacktoberfest

#172 fix(*): correct bindings in hyperlink methods - I143
  package-lock.json
  package.json
  src/FormattingToolbar/index.js
Labels: Difficulty: Starter, Type: Bug 🐛

#174 fix(schema): add tight property for lists
  src/FormattingToolbar/index.js
  src/schema.js
Labels: Difficulty: Challenging, Type: Bug 🐛

#177 chore(deps): remove unused react-flipcard dependency
  package-lock.json
  package.json
Labels: Type: Dependencies 🏠
