Repository accordproject/markdown-editor, pull requests merged in 2020-03, with the labels that each got.

#254 enchancement(SlateAsInputEditor): change multiple if condition to sin…
  src/SlateAsInputEditor/index.js
Labels: Difficulty: Medium, Type: Enhancement ✨

#246 feat(FormattingToolbar): ability to open links - #213
  src/FormattingToolbar/LinkComponent/index.js
  src/FormattingToolbar/index.js
Labels: A11Y 🔓, Difficulty: Challenging, Type: Feature Request 🛍️

#259 feat(toolbarTip): added shortcut commands in tooltip based on OS - I258
  src/FormattingToolbar/index.js
  src/FormattingToolbar/toolbarTooltip.js
  src/icons/bold.js
  src/icons/code.js
  src/icons/italic.js
Labels: A11Y 🔓, Difficulty: Medium, Type: Enhancement ✨

#260 refactor(Slate): hotkey switch-case to object literal
  src/SlateAsInputEditor/index.js
Labels: Difficulty: Medium, Type: Enhancement ✨

#263 chore(package): increment
  package-lock.json
  package.json
Labels: Type: Dependencies 🏠

#264 fix(SlateAsInputEditor): check isEditable for hotkeys
  package-lock.json
  package.json
  src/SlateAsInputEditor/index.js
  src/constants.js
Labels: Type: Bug 🐛

#269 fix(list): converts multiple line to lists - I229
  src/plugins/list.js
Labels: 0.20-ui, Difficulty: Medium, Type: Bug 🐛, Type: Enhancement ✨

#274 chore(plugins): undo pr 269
  package-lock.json
  package.json
  src/plugins/list.js
Labels: Type: Regression 🖐

#277 fix(FormattingToolbar): handle error on undo link removal
  package-lock.json
  package.json
  src/FormattingToolbar/LinkComponent/index.js
Labels: Type: Bug 🐛

#281 fix(SlateAsInputEditor): removed blank line on hitting enter after heading - I280
  src/SlateAsInputEditor/index.js
Labels: Difficulty: Medium, Type: Bug 🐛

#292 docs(*): point PRs to development
  CONTRIBUTING.md
  DEVELOPERS.md
Labels: Type: Documentation 📝

#294 style(FormattingToolbar): changed order and shortcut for code - I289-290
  src/FormattingToolbar/index.js
  src/FormattingToolbar/toolbarTooltip.js
  src/SlateAsInputEditor/index.js
  src/icons/code.js
  src/icons/navigation-right.js
Labels: Type: Enhancement ✨

#299 docs(readme): add keyboard shortcuts - #244
  README.md
Labels: Type: Documentation 📝
