Repository accordproject/markdown-editor, pull requests merged in 2020-05, with the labels that each got.

#388 fix(*): fix issue for page jump on link modal open
  src/RichTextEditor/FormattingToolbar/HyperlinkModal.js
  src/RichTextEditor/FormattingToolbar/index.js
Labels: Slate v57 ⛰️, Type: Bug 🐛

#390 refactor(src): swap class for id
  src/MarkdownTextEditor/index.js
  src/RichTextEditor/FormattingToolbar/index.js
  src/RichTextEditor/index.js
  src/RichTextEditor/tests/__snapshots__/index.test.js.snap
  src/RichTextEditor/tests/index.test.js
  src/styles.css
Labels: Type: Enhancement ✨

#395 fix(FormattingToolbar): prevent hyperlink crashing
  src/RichTextEditor/FormattingToolbar/HyperlinkModal.js
Labels: Type: Bug 🐛

#396 feat(RichTextEditor): allow consumer to prevent actions
  src/RichTextEditor/index.js
Labels: Type: Enhancement ✨
