Repository accordproject/markdown-editor, pull requests merged in 2020-04, with the labels that each got.

#304 refactor(docs): consolidate contribution guides
  CONTRIBUTING.md
  DEVELOPERS.md
Labels: Type: Documentation 📝

#306 doc(README) Add instructions for using the AP README badge
  README.md
Labels: Type: Documentation 📝

#310 refactor(docs): consolidate contribution guides
  CONTRIBUTING.md
  DEVELOPERS.md
  README.md
Labels: Type: Documentation 📝

#315 feat(ToolbarMenu): sticky formatting toolbar position - I314
  examples/src/index.css
  examples/src/index.js
  src/RichTextEditor/FormattingToolbar/ToolbarMenu.js
  src/RichTextEditor/FormattingToolbar/index.js
  src/RichTextEditor/index.js
  src/RichTextEditor/tests/__snapshots__/index.test.js.snap
  src/RichTextEditor/tests/index.test.js
  src/styles.css
Labels: Type: Enhancement ✨

#371 fix(utilities): handle block toggles - I323
  src/RichTextEditor/utilities/toolbarHelpers.js
Labels: Slate57

#374 fix(RichTextEditor): delete fragment on cut - I331
  src/RichTextEditor/index.js
Labels: Slate57

#375 fix(HyperlinkModal): fixed hotkey link removal undo - I352
  src/RichTextEditor/FormattingToolbar/HyperlinkModal.js
Labels: Slate57

#383 chore(deps): update transforms to 0.11.2
  package-lock.json
  package.json
Labels: Type: Dependencies 🏠

#386 feat(hyperlink Modal): fix hyperlink modal accepts invalid urls
  src/RichTextEditor/FormattingToolbar/HyperlinkModal.js
Labels: Type: Enhancement ✨
